import type {
  AuditLogItem,
  Case,
  CaseCycle,
  CaseRevision,
  CaseV2,
  DeploymentRun,
  DiagnosisRun,
  Finding,
  FindingComment,
  FindingPullRequest,
  FindingRevision,
  FindingType,
  FixAttempt,
  Group,
  GroupV2,
  JiraStatus,
  LegacyFinding,
  MergeBatch,
  Project,
  PullRequest,
  Severity,
  Stage,
  Ticket,
  User,
  Environment,
  FixPipelineStatus,
  UatStatus,
  DiagnosisStatus,
  AnalysisReview,
  VerificationRecord,
} from '../types';

const DAY = 86400000;
const now = new Date('2026-09-04T09:30:00+08:00').getTime();

const iso = (daysAgo: number, hours = 0) => new Date(now - daysAgo * DAY - hours * 3600000).toISOString();

export const USERS: User[] = [
  {
    id: 'u_admin',
    email: 'admin@company.com',
    name: '王鹤',
    role: 'ADMIN',
    authProvider: 'GOOGLE',
    groupIds: ['g_sre'],
    status: 'ACTIVE',
    managedProjectIds: [],
    lastLoginAt: iso(0, 2),
    createdAt: iso(210),
  },
  {
    id: 'u_zhang',
    email: 'zhangsan@company.com',
    name: '张三',
    role: 'OWNER',
    authProvider: 'GOOGLE',
    groupIds: ['g_fe', 'g_acct'],
    status: 'ACTIVE',
    managedProjectIds: ['p_acct'],
    lastLoginAt: iso(0, 5),
    createdAt: iso(180),
  },
  {
    id: 'u_li',
    email: 'lisi@company.com',
    name: '李四',
    role: 'OWNER',
    authProvider: 'GOOGLE',
    groupIds: ['g_pay'],
    status: 'ACTIVE',
    managedProjectIds: ['p_pay'],
    lastLoginAt: iso(1, 3),
    createdAt: iso(165),
  },
  {
    id: 'u_zhao',
    email: 'zhaowu@company.com',
    name: '王五',
    role: 'OWNER',
    authProvider: 'SSO',
    groupIds: ['g_cs'],
    status: 'ACTIVE',
    managedProjectIds: ['p_cs'],
    lastLoginAt: iso(2),
    createdAt: iso(120),
  },
  {
    id: 'u_qian',
    email: 'qianqi@company.com',
    name: '钱七',
    role: 'STAFF',
    staffType: 'DEV',
    authProvider: 'GOOGLE',
    groupIds: ['g_fe'],
    status: 'ACTIVE',
    managedProjectIds: [],
    lastLoginAt: iso(0, 9),
    createdAt: iso(150),
  },
  {
    id: 'u_sun',
    email: 'sunba@company.com',
    name: '孙八',
    role: 'STAFF',
    staffType: 'DEV',
    authProvider: 'GOOGLE',
    groupIds: ['g_acct'],
    status: 'ACTIVE',
    managedProjectIds: [],
    lastLoginAt: iso(3),
    createdAt: iso(140),
  },
  {
    id: 'u_zhou',
    email: 'zhoujiu@company.com',
    name: '周九',
    role: 'STAFF',
    staffType: 'DEV',
    authProvider: 'PASSWORD',
    groupIds: ['g_pay'],
    status: 'ACTIVE',
    managedProjectIds: [],
    lastLoginAt: iso(1, 6),
    createdAt: iso(96),
  },
  {
    id: 'u_wu',
    email: 'wushi@company.com',
    name: '吴十',
    role: 'STAFF',
    staffType: 'TESTER',
    authProvider: 'GOOGLE',
    groupIds: ['g_cs', 'g_qa'],
    status: 'ACTIVE',
    managedProjectIds: [],
    lastLoginAt: iso(6),
    createdAt: iso(70),
  },
  {
    id: 'u_pending',
    email: 'chene@company.com',
    name: '陈二',
    role: 'STAFF',
    staffType: 'DEV',
    authProvider: 'GOOGLE',
    groupIds: [],
    status: 'PENDING',
    managedProjectIds: [],
    lastLoginAt: '',
    createdAt: iso(4),
  },
];

export const GROUPS: Group[] = [
  { id: 'g_fe', name: '前端平台组', description: 'Web 容器与全部微前端子应用', memberCount: 8, autoSync: 'JIRA_ROLE' },
  { id: 'g_acct', name: '账户服务组', description: 'account-ms / customer-adapter', memberCount: 6, autoSync: 'JIRA_ROLE' },
  { id: 'g_pay', name: '支付服务组', description: 'payment-ms、渠道网关', memberCount: 7, autoSync: 'LDAP' },
  { id: 'g_cs', name: '客户服务组', description: 'customer-ms 与工台', memberCount: 5, autoSync: 'MANUAL' },
  { id: 'g_qa', name: '质量保障组', description: 'UAT 验证与回归', memberCount: 4, autoSync: 'LDAP' },
  { id: 'g_sre', name: 'SRE', description: '日志、发布与告警', memberCount: 3, autoSync: 'MANUAL' },
];

export const GROUPS_V2: GroupV2[] = [
  {
    id: 'g_fe',
    name: '前端平台组',
    description: 'Web 容器与全部微前端子应用',
    organizationId: 'org_1',
    ownerId: 'u_zhang',
    memberIds: ['u_zhang', 'u_zhou'],
    projectIds: ['p_acct'],
    createdAt: iso(180),
  },
  {
    id: 'g_acct',
    name: '账户服务组',
    description: 'account-ms / customer-adapter',
    organizationId: 'org_1',
    ownerId: 'u_zhang',
    memberIds: ['u_zhang'],
    projectIds: ['p_acct'],
    createdAt: iso(180),
  },
  {
    id: 'g_pay',
    name: '支付服务组',
    description: 'payment-ms、渠道网关',
    organizationId: 'org_1',
    ownerId: 'u_li',
    memberIds: ['u_li'],
    projectIds: ['p_pay'],
    createdAt: iso(165),
  },
  {
    id: 'g_cs',
    name: '客户服务组',
    description: 'customer-ms 与工台',
    organizationId: 'org_1',
    ownerId: 'u_zhao',
    memberIds: ['u_zhao'],
    projectIds: ['p_cs'],
    createdAt: iso(120),
  },
];

/* -------- 生命周期辅助数据（§4） -------- */

export const CASE_CYCLES: CaseCycle[] = [
  { id: 'cy_1_1', caseId: 'c_1', cycleNo: 1, status: 'ACTIVE', openedAt: iso(0, 3) },
  { id: 'cy_2_1', caseId: 'c_2', cycleNo: 1, status: 'ACTIVE', openedAt: iso(1, 2) },
  { id: 'cy_3_1', caseId: 'c_3', cycleNo: 1, status: 'ACTIVE', openedAt: iso(2, 1) },
  { id: 'cy_4_1', caseId: 'c_4', cycleNo: 1, status: 'ACTIVE', openedAt: iso(3, 4) },
  { id: 'cy_5_1', caseId: 'c_5', cycleNo: 1, status: 'ACTIVE', openedAt: iso(4, 2) },
  { id: 'cy_6_1', caseId: 'c_6', cycleNo: 1, status: 'CLOSED', openedAt: iso(10), closedAt: iso(5) },
  { id: 'cy_6_2', caseId: 'c_6', cycleNo: 2, status: 'ACTIVE', openedReason: 'VERIFICATION_FAILED', openedAt: iso(5) },
  { id: 'cy_7_1', caseId: 'c_7', cycleNo: 1, status: 'ACTIVE', openedAt: iso(1, 5) },
  { id: 'cy_8_1', caseId: 'c_8', cycleNo: 1, status: 'ACTIVE', openedAt: iso(5, 3) },
  { id: 'cy_9_1', caseId: 'c_9', cycleNo: 1, status: 'ACTIVE', openedAt: iso(7, 2) },
  { id: 'cy_10_1', caseId: 'c_10', cycleNo: 1, status: 'CLOSED', openedAt: iso(12), closedAt: iso(6) },
];

export const CASE_REVISIONS: CaseRevision[] = [
  { id: 'cr_1', caseId: 'c_1', caseCycleId: 'cy_1_1', revisionNo: 1, title: '登录页面 KYC 上传后无响应', description: '用户上传身份证照片后，页面卡在 loading 状态，无错误提示', changedBy: 'tester@company.com', createdAt: iso(0, 3) },
  { id: 'cr_2', caseId: 'c_2', caseCycleId: 'cy_2_1', revisionNo: 1, title: '账户资料修改保存失败', description: '修改手机号后点击保存，提示"系统错误"', changedBy: 'user@company.com', createdAt: iso(1, 2) },
  { id: 'cr_3', caseId: 'c_3', caseCycleId: 'cy_3_1', revisionNo: 1, title: '支付回调通知延迟', description: '用户支付成功后，订单状态更新延迟超过 5 分钟', changedBy: 'merchant@company.com', createdAt: iso(2, 1) },
  { id: 'cr_4', caseId: 'c_4', caseCycleId: 'cy_4_1', revisionNo: 1, title: '工台搜索功能异常', description: '输入客户姓名后无搜索结果返回', changedBy: 'cs_staff@company.com', createdAt: iso(3, 4) },
  { id: 'cr_5', caseId: 'c_5', caseCycleId: 'cy_5_1', revisionNo: 1, title: 'UAT 环境支付渠道切换后金额丢失', description: '切换支付渠道后，金额字段未刷新', changedBy: 'tester@company.com', createdAt: iso(4, 2) },
  { id: 'cr_6_1', caseId: 'c_6', caseCycleId: 'cy_6_1', revisionNo: 1, title: '对账文件日期格式不一致导致导入失败', description: '跨月对账文件日期格式从 yyyyMMdd 变为 yyyy-MM-dd', changedBy: 'ops@company.com', createdAt: iso(10) },
  { id: 'cr_6_2', caseId: 'c_6', caseCycleId: 'cy_6_2', revisionNo: 1, title: '对账文件日期格式不一致导致导入失败', description: '验证发现跨月边界仍有漏单', changedBy: 'u_zhao', changeReason: '验证失败 Reopen', createdAt: iso(5) },
  { id: 'cr_7', caseId: 'c_7', caseCycleId: 'cy_7_1', revisionNo: 1, title: '额度查询接口偶发 504', description: '高峰时段额度查询接口超时返回 504', changedBy: 'user@company.com', createdAt: iso(1, 5) },
  { id: 'cr_8', caseId: 'c_8', caseCycleId: 'cy_8_1', revisionNo: 1, title: '收银台支付完成后订单状态未更新', description: '用户支付成功后收银台仍显示"待支付"', changedBy: 'merchant@company.com', createdAt: iso(5, 3) },
  { id: 'cr_9', caseId: 'c_9', caseCycleId: 'cy_9_1', revisionNo: 1, title: '投诉单附件上传后预览空白', description: '上传 PNG 图片后预览区域显示空白', changedBy: 'cs_staff@company.com', createdAt: iso(7, 2) },
  { id: 'cr_10', caseId: 'c_10', caseCycleId: 'cy_10_1', revisionNo: 1, title: '批量转账文件模板格式错误导致导入失败', description: 'Excel 模板列顺序与接口不匹配', changedBy: 'ops@company.com', createdAt: iso(12) },
];

export const FINDING_REVISIONS: FindingRevision[] = [
  { id: 'fr_2a', findingId: 'f_2a', caseCycleId: 'cy_2_1', revisionNo: 1, title: 'customer-adapter 连接池耗尽', rootCause: '连接池 maxActive=8 在高并发下耗尽', recommendation: '扩容至 32 并增加降级熔断', confidence: 0.86, status: 'CURRENT', createdAt: iso(1, 1) },
  { id: 'fr_2b', findingId: 'f_2b', caseCycleId: 'cy_2_1', revisionNo: 1, title: '前端拼音字段被覆盖', rootCause: 'onLanguageChange 里 setFieldsValue 覆盖了 namePinyin', recommendation: '切换语言时保留 store 原值', confidence: 0.92, status: 'CURRENT', createdAt: iso(1, 0) },
  { id: 'fr_3a', findingId: 'f_3a', caseCycleId: 'cy_3_1', revisionNo: 1, title: '退款幂等键缺失', rootCause: '退款接口未包含唯一幂等键，网络重试导致重复退款', recommendation: '增加基于 orderId+timestamp 的幂等键', confidence: 0.91, status: 'CURRENT', createdAt: iso(2, 0) },
  { id: 'fr_3b', findingId: 'f_3b', caseCycleId: 'cy_3_1', revisionNo: 1, title: '回调签名校验时区偏移', rootCause: '签名校验使用 UTC 但渠道发送 CST，导致偏移 8 小时', recommendation: '统一使用 ISO-8601 并显式指定时区', confidence: 0.78, status: 'CURRENT', createdAt: iso(1, 20) },
  { id: 'fr_4a', findingId: 'f_4a', caseCycleId: 'cy_4_1', revisionNo: 1, title: '搜索接口分页参数缺失', rootCause: 'customer-ms 搜索接口未传 pageSize 默认值导致返回 0 条', recommendation: '设置默认 pageSize=20', confidence: 0.88, status: 'CURRENT', createdAt: iso(3, 2) },
  { id: 'fr_5a', findingId: 'f_5a', caseCycleId: 'cy_5_1', revisionNo: 1, title: '渠道切换后金额状态未重置', rootCause: '切换渠道时未触发金额字段重新计算', recommendation: '在渠道 onChange 中触发金额 recalculating', confidence: 0.85, status: 'CURRENT', createdAt: iso(4, 1) },
  { id: 'fr_6a', findingId: 'f_6a', caseCycleId: 'cy_6_2', revisionNo: 1, title: '日期解析器未兼容新格式', rootCause: 'SimpleDateFormat 仅支持 yyyyMMdd', recommendation: '增加 yyyy-MM-dd 格式兼容', confidence: 0.95, status: 'CURRENT', createdAt: iso(5) },
];

export const FINDING_COMMENTS: FindingComment[] = [
  { id: 'fc_1', findingId: 'f_2a', caseCycleId: 'cy_2_1', authorType: 'USER', authorUserId: 'u_zhang', content: '连接池扩容是否会影响其他服务？', createdAt: iso(0, 20) },
  { id: 'fc_2', findingId: 'f_2a', caseCycleId: 'cy_2_1', authorType: 'DEVIN', content: 'customer-adapter 独立部署，扩容不影响 account-ms。建议同时补充连接泄漏检测。', diagnosisRunId: 'dr_2', createdAt: iso(0, 19) },
  { id: 'fc_3', findingId: 'f_3a', caseCycleId: 'cy_3_1', authorType: 'USER', authorUserId: 'u_li', content: '幂等键用 orderId+timestamp 可能在极端并发下重复，建议加 UUID', createdAt: iso(1, 18) },
  { id: 'fc_4', findingId: 'f_3a', caseCycleId: 'cy_3_1', authorType: 'SYSTEM', content: 'Finding 已选择 AUTO_FIX，等待执行', createdAt: iso(1, 16) },
];

export const DIAGNOSIS_RUNS: DiagnosisRun[] = [
  { id: 'dr_2', caseId: 'c_2', caseCycleId: 'cy_2_1', mode: 'DIAGNOSE', status: 'COMPLETED', provider: 'DEVIN', providerSessionId: 'sess_2a', caseRevisionId: 'cr_2', createdAt: iso(1, 2), updatedAt: iso(1, 0) },
  { id: 'dr_3', caseId: 'c_3', caseCycleId: 'cy_3_1', mode: 'DIAGNOSE', status: 'COMPLETED', provider: 'DEVIN', providerSessionId: 'sess_3a', caseRevisionId: 'cr_3', createdAt: iso(2, 1), updatedAt: iso(2, 0) },
  { id: 'dr_3_fix', caseId: 'c_3', caseCycleId: 'cy_3_1', mode: 'IMPLEMENT_CHANGE', status: 'COMPLETED', provider: 'DEVIN', providerSessionId: 'sess_3_fix', createdAt: iso(1, 22), updatedAt: iso(1, 20) },
  { id: 'dr_4', caseId: 'c_4', caseCycleId: 'cy_4_1', mode: 'DIAGNOSE', status: 'COMPLETED', provider: 'DEVIN', providerSessionId: 'sess_4a', caseRevisionId: 'cr_4', createdAt: iso(3, 3), updatedAt: iso(3, 2) },
  { id: 'dr_5', caseId: 'c_5', caseCycleId: 'cy_5_1', mode: 'DIAGNOSE', status: 'COMPLETED', provider: 'DEVIN', providerSessionId: 'sess_5a', caseRevisionId: 'cr_5', createdAt: iso(4, 1), updatedAt: iso(4, 0) },
  { id: 'dr_6_1', caseId: 'c_6', caseCycleId: 'cy_6_1', mode: 'DIAGNOSE', status: 'COMPLETED', provider: 'DEVIN', providerSessionId: 'sess_6a', caseRevisionId: 'cr_6_1', createdAt: iso(9), updatedAt: iso(8) },
  { id: 'dr_6_2', caseId: 'c_6', caseCycleId: 'cy_6_2', mode: 'DIAGNOSE', status: 'COMPLETED', provider: 'DEVIN', providerSessionId: 'sess_6b', caseRevisionId: 'cr_6_2', createdAt: iso(5), updatedAt: iso(4, 20) },
];

export const FIX_ATTEMPTS: FixAttempt[] = [
  { id: 'fa_3a', caseId: 'c_3', caseCycleId: 'cy_3_1', primaryFindingId: 'f_3a', diagnosisRunId: 'dr_3_fix', attemptNo: 1, provider: 'DEVIN', providerSessionId: 'fix_3a', approvalPolicy: 'MANUAL', approvalStatus: 'APPROVED', approvedBy: 'u_li', executionStatus: 'PR_CREATED', idempotencyKey: 'idem_3a_1', createdAt: iso(1, 22), updatedAt: iso(1, 20) },
  { id: 'fa_3b', caseId: 'c_3', caseCycleId: 'cy_3_1', primaryFindingId: 'f_3b', attemptNo: 1, provider: 'DEVIN', providerSessionId: 'fix_3b', approvalPolicy: 'MANUAL', approvalStatus: 'APPROVED', approvedBy: 'u_li', executionStatus: 'PR_CREATED', idempotencyKey: 'idem_3b_1', createdAt: iso(1, 21), updatedAt: iso(1, 19) },
  { id: 'fa_5a', caseId: 'c_5', caseCycleId: 'cy_5_1', primaryFindingId: 'f_5a', attemptNo: 1, provider: 'DEVIN', approvalPolicy: 'MANUAL', approvalStatus: 'APPROVED', approvedBy: 'u_zhao', executionStatus: 'PR_CREATED', idempotencyKey: 'idem_5a_1', createdAt: iso(3, 20), updatedAt: iso(3, 18) },
];

export const PULL_REQUESTS: PullRequest[] = [
  { id: 'pr_3a', provider: 'BITBUCKET', repositoryId: 'r_5', externalId: '431', number: 431, url: 'https://bitbucket.company.com/projects/PAY/repos/payment-ms/pull-requests/431', sourceBranch: 'fix/PAY-425-idempotency', targetBranch: 'main', headSha: 'abc1234', state: 'OPEN', draft: false, mergeableState: 'CLEAN', checksStatus: 'PASSING', reviewStatus: 'APPROVED', branchProtectionStatus: 'SATISFIED', originType: 'DEVIN', originFixAttemptId: 'fa_3a', lastSyncedAt: iso(0, 1) },
  { id: 'pr_3b', provider: 'BITBUCKET', repositoryId: 'r_5', externalId: '432', number: 432, url: 'https://bitbucket.company.com/projects/PAY/repos/payment-ms/pull-requests/432', sourceBranch: 'fix/PAY-425-timezone', targetBranch: 'main', headSha: 'def5678', state: 'OPEN', draft: false, mergeableState: 'CLEAN', checksStatus: 'PASSING', reviewStatus: 'PENDING', branchProtectionStatus: 'SATISFIED', originType: 'DEVIN', originFixAttemptId: 'fa_3b', lastSyncedAt: iso(0, 1) },
  { id: 'pr_5a', provider: 'BITBUCKET', repositoryId: 'r_5', externalId: '440', number: 440, url: 'https://bitbucket.company.com/projects/PAY/repos/payment-ms/pull-requests/440', sourceBranch: 'fix/channel-amount-reset', targetBranch: 'main', headSha: 'ghi9012', state: 'MERGED', draft: false, mergeableState: 'CLEAN', checksStatus: 'PASSING', reviewStatus: 'APPROVED', branchProtectionStatus: 'SATISFIED', originType: 'DEVIN', originFixAttemptId: 'fa_5a', mergedSha: 'ghi9012', mergedAt: iso(2, 10), lastSyncedAt: iso(2, 10) },
  { id: 'pr_6a', provider: 'BITBUCKET', repositoryId: 'r_2', externalId: '201', number: 201, url: 'https://bitbucket.company.com/projects/ACCT/repos/account-ms/pull-requests/201', sourceBranch: 'fix/date-format', targetBranch: 'main', headSha: 'jkl3456', state: 'MERGED', draft: false, mergeableState: 'CLEAN', checksStatus: 'PASSING', reviewStatus: 'APPROVED', branchProtectionStatus: 'SATISFIED', originType: 'DEVIN', mergedSha: 'jkl3456', mergedAt: iso(6), lastSyncedAt: iso(6) },
];

export const FINDING_PULL_REQUESTS: FindingPullRequest[] = [
  { id: 'fpr_3a', caseCycleId: 'cy_3_1', findingId: 'f_3a', pullRequestId: 'pr_3a', relationType: 'PRIMARY', source: 'DEVIN', isCurrent: true, linkedBy: 'devin', createdAt: iso(1, 20), pullRequest: PULL_REQUESTS[0] },
  { id: 'fpr_3b', caseCycleId: 'cy_3_1', findingId: 'f_3b', pullRequestId: 'pr_3b', relationType: 'PRIMARY', source: 'DEVIN', isCurrent: true, linkedBy: 'devin', createdAt: iso(1, 19), pullRequest: PULL_REQUESTS[1] },
  { id: 'fpr_5a', caseCycleId: 'cy_5_1', findingId: 'f_5a', pullRequestId: 'pr_5a', relationType: 'PRIMARY', source: 'DEVIN', isCurrent: true, linkedBy: 'devin', createdAt: iso(3, 18), pullRequest: PULL_REQUESTS[2] },
  { id: 'fpr_6a', caseCycleId: 'cy_6_2', findingId: 'f_6a', pullRequestId: 'pr_6a', relationType: 'PRIMARY', source: 'DEVIN', isCurrent: true, linkedBy: 'devin', createdAt: iso(6), pullRequest: PULL_REQUESTS[3] },
];

export const DEPLOYMENT_RUNS: DeploymentRun[] = [
  { id: 'dep_5a', caseId: 'c_5', caseCycleId: 'cy_5_1', repositoryId: 'r_5', environment: 'UAT', workflowName: 'payment-ms-uat', commitSha: 'ghi9012', status: 'SUCCEEDED', attemptNo: 1, url: 'https://ci.company.com/runs/dep-5a', startedAt: iso(2, 10), finishedAt: iso(2, 8) },
  { id: 'dep_6a', caseId: 'c_6', caseCycleId: 'cy_6_2', repositoryId: 'r_2', environment: 'PROD', workflowName: 'account-ms-deploy', commitSha: 'jkl3456', status: 'FAILED', attemptNo: 1, url: 'https://ci.company.com/runs/dep-6a', startedAt: iso(5, 20), finishedAt: iso(5, 18) },
  { id: 'dep_6b', caseId: 'c_6', caseCycleId: 'cy_6_2', repositoryId: 'r_1', environment: 'PROD', workflowName: 'account-web-deploy', commitSha: 'jkl3456', status: 'SUCCEEDED', attemptNo: 1, url: 'https://ci.company.com/runs/dep-6b', startedAt: iso(5, 20), finishedAt: iso(5, 19) },
];

export const VERIFICATION_RECORDS: VerificationRecord[] = [
  { id: 'vr_6_1', caseId: 'c_6', caseCycleId: 'cy_6_1', result: 'FAILED', comment: '跨月边界仍有漏单', verifiedBy: 'u_wu', createdAt: iso(5) },
];

export const MERGE_BATCHES: MergeBatch[] = [];

/* -------- Finding 构造辅助 -------- */

function makeFinding(
  id: string, findingKey: string, caseId: string, caseCycleId: string,
  type: FindingType, source: Finding['source'], title: string,
  analysisStatus: Finding['analysisStatus'],
  resolutionType: Finding['resolutionType'],
  resolutionStatus: Finding['resolutionStatus'],
  revisionId: string,
): Finding {
  const rev = FINDING_REVISIONS.find((r) => r.id === revisionId)!;
  return {
    id, findingKey, caseId, caseCycleId,
    primaryApplicationId: caseId,
    type, source, title,
    analysisStatus, resolutionType, resolutionStatus,
    isCurrent: true, currentRevisionId: revisionId,
    createdAt: rev.createdAt, updatedAt: rev.createdAt,
    currentRevision: rev,
    revisions: [rev],
    comments: FINDING_COMMENTS.filter((c) => c.findingId === id),
    fixAttempts: FIX_ATTEMPTS.filter((a) => a.primaryFindingId === id),
    pullRequests: FINDING_PULL_REQUESTS.filter((fp) => fp.findingId === id),
  };
}

/* -------- CASES_V2（覆盖主流程各状态） -------- */

export const CASES_V2: CaseV2[] = [
  {
    id: 'c_1',
    caseKey: 'SH-20260908-D912E568',
    projectId: 'p_acct',
    groupId: 'g_acct',
    title: '登录页面 KYC 上传后无响应',
    description: '用户上传身份证照片后，页面卡在 loading 状态，无错误提示',
    status: 'PENDING_ANALYSIS',
    currentCycleId: 'cy_1_1',
    assigneeId: undefined,
    environment: 'PROD',
    severity: 'Major',
    pageUrl: 'https://account.company.com/kyc/upload',
    buildVersion: '2.14.3',
    reporter: 'tester@company.com',
    reportedAt: iso(0, 3),
    updatedAt: iso(0, 3),
    version: 1,
    currentCycle: CASE_CYCLES[0],
    cycles: [CASE_CYCLES[0]],
    currentRevision: CASE_REVISIONS[0],
    revisions: [CASE_REVISIONS[0]],
    findings: [],
    pullRequests: [],
    deploymentRuns: [],
    verificationRecords: [],
    mergeBatches: [],
    diagnosisRuns: [],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
  {
    id: 'c_2',
    caseKey: 'SH-20260907-A1B2C3D4',
    projectId: 'p_acct',
    groupId: 'g_acct',
    title: '账户资料修改保存失败',
    description: '修改手机号后点击保存，提示"系统错误"',
    status: 'ANALYSIS_COMPLETED',
    currentCycleId: 'cy_2_1',
    assigneeId: 'u_zhang',
    environment: 'PROD',
    severity: 'Critical',
    pageUrl: 'https://account.company.com/profile',
    buildVersion: '2.14.3',
    reporter: 'user@company.com',
    reportedAt: iso(1, 2),
    updatedAt: iso(0, 5),
    version: 1,
    currentCycle: CASE_CYCLES[1],
    cycles: [CASE_CYCLES[1]],
    currentRevision: CASE_REVISIONS[1],
    revisions: [CASE_REVISIONS[1]],
    findings: [
      makeFinding('f_2a', 'FND-2a', 'c_2', 'cy_2_1', 'BACKEND', 'DEVIN', 'customer-adapter 连接池耗尽', 'ACCEPTED', 'AUTO_FIX', 'NOT_STARTED', 'fr_2a'),
      makeFinding('f_2b', 'FND-2b', 'c_2', 'cy_2_1', 'FRONTEND', 'DEVIN', '前端拼音字段被覆盖', 'DRAFT', undefined, 'NOT_STARTED', 'fr_2b'),
    ],
    pullRequests: [],
    deploymentRuns: [],
    verificationRecords: [],
    mergeBatches: [],
    diagnosisRuns: [DIAGNOSIS_RUNS[0]],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
  {
    id: 'c_3',
    caseKey: 'SH-20260906-E5F6G7H8',
    projectId: 'p_pay',
    groupId: 'g_pay',
    title: '支付回调通知延迟',
    description: '用户支付成功后，订单状态更新延迟超过 5 分钟',
    status: 'DEVELOPING',
    currentCycleId: 'cy_3_1',
    assigneeId: 'u_li',
    environment: 'PROD',
    severity: 'Major',
    pageUrl: 'https://payment.company.com/callback',
    buildVersion: '1.8.2',
    reporter: 'merchant@company.com',
    reportedAt: iso(2, 1),
    updatedAt: iso(0, 8),
    version: 1,
    currentCycle: CASE_CYCLES[2],
    cycles: [CASE_CYCLES[2]],
    currentRevision: CASE_REVISIONS[2],
    revisions: [CASE_REVISIONS[2]],
    findings: [
      makeFinding('f_3a', 'FND-3a', 'c_3', 'cy_3_1', 'BACKEND', 'DEVIN', '退款幂等键缺失', 'ACCEPTED', 'AUTO_FIX', 'READY_TO_MERGE', 'fr_3a'),
      makeFinding('f_3b', 'FND-3b', 'c_3', 'cy_3_1', 'BACKEND', 'DEVIN', '回调签名校验时区偏移', 'ACCEPTED', 'MANUAL_FIX', 'IN_PROGRESS', 'fr_3b'),
    ],
    pullRequests: [PULL_REQUESTS[0], PULL_REQUESTS[1]],
    deploymentRuns: [],
    verificationRecords: [],
    mergeBatches: [],
    diagnosisRuns: [DIAGNOSIS_RUNS[1], DIAGNOSIS_RUNS[2]],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
  {
    id: 'c_4',
    caseKey: 'SH-20260905-I9J0K1L2',
    projectId: 'p_cs',
    groupId: 'g_cs',
    title: '工台搜索功能异常',
    description: '输入客户姓名后无搜索结果返回',
    status: 'PENDING_VERIFICATION',
    currentCycleId: 'cy_4_1',
    assigneeId: 'u_zhao',
    environment: 'UAT',
    severity: 'Minor',
    pageUrl: 'https://cs.company.com/workbench',
    buildVersion: '3.2.1',
    reporter: 'cs_staff@company.com',
    reportedAt: iso(3, 4),
    updatedAt: iso(0, 2),
    version: 1,
    currentCycle: CASE_CYCLES[3],
    cycles: [CASE_CYCLES[3]],
    currentRevision: CASE_REVISIONS[3],
    revisions: [CASE_REVISIONS[3]],
    findings: [
      makeFinding('f_4a', 'FND-4a', 'c_4', 'cy_4_1', 'BACKEND', 'DEVIN', '搜索接口分页参数缺失', 'ACCEPTED', 'MANUAL_FIX', 'COMPLETED', 'fr_4a'),
    ],
    pullRequests: [],
    deploymentRuns: [],
    verificationRecords: [],
    mergeBatches: [],
    diagnosisRuns: [DIAGNOSIS_RUNS[3]],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
  {
    id: 'c_5',
    caseKey: 'SH-20260904-M3N4O5P6',
    projectId: 'p_pay',
    groupId: 'g_pay',
    title: 'UAT 环境支付渠道切换后金额丢失',
    description: '切换支付渠道后，金额字段未刷新',
    status: 'DEPLOY_FAILED',
    currentCycleId: 'cy_5_1',
    assigneeId: 'u_zhao',
    environment: 'UAT',
    severity: 'Major',
    pageUrl: 'https://payment.company.com/uat/cashier',
    buildVersion: '1.9.4',
    reporter: 'tester@company.com',
    reportedAt: iso(4, 2),
    updatedAt: iso(2, 8),
    version: 1,
    currentCycle: CASE_CYCLES[4],
    cycles: [CASE_CYCLES[4]],
    currentRevision: CASE_REVISIONS[4],
    revisions: [CASE_REVISIONS[4]],
    findings: [
      makeFinding('f_5a', 'FND-5a', 'c_5', 'cy_5_1', 'FRONTEND', 'DEVIN', '渠道切换后金额状态未重置', 'ACCEPTED', 'AUTO_FIX', 'COMPLETED', 'fr_5a'),
    ],
    pullRequests: [PULL_REQUESTS[2]],
    deploymentRuns: [DEPLOYMENT_RUNS[0]],
    verificationRecords: [],
    mergeBatches: [],
    diagnosisRuns: [DIAGNOSIS_RUNS[4]],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
  {
    id: 'c_6',
    caseKey: 'SH-20260830-Q7R8S9T0',
    projectId: 'p_acct',
    groupId: 'g_acct',
    title: '对账文件日期格式不一致导致导入失败',
    description: '跨月对账文件日期格式从 yyyyMMdd 变为 yyyy-MM-dd，验证发现仍有漏单',
    status: 'DEPLOY_FAILED',
    currentCycleId: 'cy_6_2',
    assigneeId: 'u_zhang',
    environment: 'PROD',
    severity: 'Critical',
    pageUrl: 'https://account.company.com/reconciliation',
    buildVersion: '5.8.0',
    reporter: 'ops@company.com',
    reportedAt: iso(10),
    updatedAt: iso(5, 18),
    version: 2,
    currentCycle: CASE_CYCLES[6],
    cycles: [CASE_CYCLES[5], CASE_CYCLES[6]],
    currentRevision: CASE_REVISIONS[6],
    revisions: [CASE_REVISIONS[5], CASE_REVISIONS[6]],
    findings: [
      makeFinding('f_6a', 'FND-6a', 'c_6', 'cy_6_2', 'BACKEND', 'DEVIN', '日期解析器未兼容新格式', 'ACCEPTED', 'AUTO_FIX', 'COMPLETED', 'fr_6a'),
    ],
    pullRequests: [PULL_REQUESTS[3]],
    deploymentRuns: [DEPLOYMENT_RUNS[1], DEPLOYMENT_RUNS[2]],
    verificationRecords: [VERIFICATION_RECORDS[0]],
    mergeBatches: [],
    diagnosisRuns: [DIAGNOSIS_RUNS[5], DIAGNOSIS_RUNS[6]],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
  {
    id: 'c_7',
    caseKey: 'SH-20260907-ANLZ1234',
    projectId: 'p_acct',
    groupId: 'g_acct',
    title: '额度查询接口偶发 504',
    description: '高峰时段额度查询接口超时返回 504',
    status: 'ANALYZING',
    currentCycleId: 'cy_7_1',
    assigneeId: 'u_sun',
    environment: 'PROD',
    severity: 'Critical',
    pageUrl: 'https://account.company.com/quota',
    buildVersion: '5.8.0',
    reporter: 'user@company.com',
    reportedAt: iso(1, 5),
    updatedAt: iso(1, 3),
    version: 1,
    currentCycle: CASE_CYCLES[7],
    cycles: [CASE_CYCLES[7]],
    currentRevision: CASE_REVISIONS[7],
    revisions: [CASE_REVISIONS[7]],
    findings: [],
    pullRequests: [],
    deploymentRuns: [],
    verificationRecords: [],
    mergeBatches: [],
    diagnosisRuns: [],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
  {
    id: 'c_8',
    caseKey: 'SH-20260903-DEPL5678',
    projectId: 'p_pay',
    groupId: 'g_pay',
    title: '收银台支付完成后订单状态未更新',
    description: '用户支付成功后收银台仍显示"待支付"',
    status: 'DEPLOYING',
    currentCycleId: 'cy_8_1',
    assigneeId: 'u_zhou',
    environment: 'PROD',
    severity: 'Critical',
    pageUrl: 'https://payment.company.com/cashier',
    buildVersion: '3.2.7',
    reporter: 'merchant@company.com',
    reportedAt: iso(5, 3),
    updatedAt: iso(1, 10),
    version: 1,
    currentCycle: CASE_CYCLES[8],
    cycles: [CASE_CYCLES[8]],
    currentRevision: CASE_REVISIONS[8],
    revisions: [CASE_REVISIONS[8]],
    findings: [],
    pullRequests: [],
    deploymentRuns: [],
    verificationRecords: [],
    mergeBatches: [],
    diagnosisRuns: [],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
  {
    id: 'c_9',
    caseKey: 'SH-20260901-DPLY9012',
    projectId: 'p_cs',
    groupId: 'g_cs',
    title: '投诉单附件上传后预览空白',
    description: '上传 PNG 图片后预览区域显示空白',
    status: 'DEPLOYED',
    currentCycleId: 'cy_9_1',
    assigneeId: 'u_wu',
    environment: 'PROD',
    severity: 'Minor',
    pageUrl: 'https://cs.company.com/complaint',
    buildVersion: '4.1.2',
    reporter: 'cs_staff@company.com',
    reportedAt: iso(7, 2),
    updatedAt: iso(3, 5),
    version: 1,
    currentCycle: CASE_CYCLES[9],
    cycles: [CASE_CYCLES[9]],
    currentRevision: CASE_REVISIONS[9],
    revisions: [CASE_REVISIONS[9]],
    findings: [],
    pullRequests: [],
    deploymentRuns: [],
    verificationRecords: [],
    mergeBatches: [],
    diagnosisRuns: [],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
  {
    id: 'c_10',
    caseKey: 'SH-20260827-CMPL3456',
    projectId: 'p_acct',
    groupId: 'g_acct',
    title: '批量转账文件模板格式错误导致导入失败',
    description: 'Excel 模板列顺序与接口不匹配',
    status: 'COMPLETED',
    currentCycleId: 'cy_10_1',
    assigneeId: 'u_sun',
    environment: 'PROD',
    severity: 'Major',
    pageUrl: 'https://account.company.com/batch-transfer',
    buildVersion: '5.7.2',
    reporter: 'ops@company.com',
    reportedAt: iso(12),
    updatedAt: iso(6),
    version: 1,
    currentCycle: CASE_CYCLES[10],
    cycles: [CASE_CYCLES[10]],
    currentRevision: CASE_REVISIONS[10],
    revisions: [CASE_REVISIONS[10]],
    findings: [],
    pullRequests: [],
    deploymentRuns: [],
    verificationRecords: [],
    mergeBatches: [],
    diagnosisRuns: [],
    network: [],
    consoleLogs: [],
    stacks: [],
    evidenceChain: [],
  },
];

const jiraSite = 'https://jira.company.com';

export const PROJECTS: Project[] = [
  {
    id: 'p_acct',
    projectKey: 'account-center',
    name: '账户中心',
    description: '登录、账户资料、额度与 KYC 流程',
    ownerId: 'u_zhang',
    access: { groupIds: ['g_fe', 'g_acct', 'g_qa'], userIds: ['u_zhou'] },
    status: 'ACTIVE',
    repos: [
      {
        id: 'r_1',
        repoType: 'FRONTEND',
        provider: 'BITBUCKET',
        repoProject: 'FE',
        repoSlug: 'account-web',
        defaultBranch: 'main',
        urlPatterns: [],
        subAppKey: 'account',
        verifyState: 'VERIFIED',
        lastCommit: 'a13f9c2',
        latestTag: 'v2.14.1',
      },
      {
        id: 'r_2',
        repoType: 'BACKEND',
        provider: 'BITBUCKET',
        repoProject: 'ACCT',
        repoSlug: 'account-ms',
        defaultBranch: 'main',
        urlPatterns: ['/api/account/**'],
        verifyState: 'VERIFIED',
        lastCommit: '9c21bb0',
        latestTag: 'v5.8.0',
      },
      {
        id: 'r_3',
        repoType: 'BACKEND',
        provider: 'BITBUCKET',
        repoProject: 'ACCT',
        repoSlug: 'customer-adapter',
        defaultBranch: 'master',
        urlPatterns: ['/api/customer/adapter/**'],
        verifyState: 'FAILED',
        lastCommit: '',
        latestTag: '',
      },
    ],
    urlMappings: [
      { id: 'm_1', pattern: '/api/account/**', service: 'account-ms', repoId: 'r_2' },
      { id: 'm_2', pattern: '/api/customer/adapter/**', service: 'customer-adapter', repoId: 'r_3' },
      { id: 'm_3', pattern: '/account/*', service: 'fe/account-web', repoId: 'r_1' },
    ],
    logging: {
      provider: 'ELASTIC',
      baseUrl: 'https://kibana.company.com/app/discover',
      indexPattern: 'account-ms-*,customer-adapter-*',
      versionMapping: 'TAG',
      fieldMap: {
        timestamp: '@timestamp',
        level: 'level',
        traceId: 'traceId',
        message: 'message',
        stackTrace: 'exception.stack_trace',
        service: 'service.name',
      },
      verifyState: 'VERIFIED',
      docCount7d: 1_284_930,
    },
    jira: {
      site: jiraSite,
      projectKey: 'ACCOUNT',
      issueType: 'Bug',
      descriptionTemplate: '问题描述 / 复现步骤 / 日志与 Trace / AI 诊断结论 / 建议修复',
      autoCreate: true,
    },
    uat: { pipelineId: 'account-ms-uat', deployMethod: 'WEBHOOK_DIRECT', enabled: true },
    capability: { aiDiagnosis: true, sourceAnalysis: true, autoFix: true, approvalMode: 'REVIEW_REQUIRED' },
    createdAt: iso(180),
    updatedAt: iso(2),
  },
  {
    id: 'p_pay',
    projectKey: 'payment-gateway',
    name: '支付网关',
    description: '渠道下单、回调、对账与退款',
    ownerId: 'u_li',
    access: { groupIds: ['g_pay', 'g_sre'], userIds: [] },
    status: 'ACTIVE',
    repos: [
      {
        id: 'r_4',
        repoType: 'FRONTEND',
        provider: 'BITBUCKET',
        repoProject: 'FE',
        repoSlug: 'cashier-web',
        defaultBranch: 'main',
        urlPatterns: [],
        subAppKey: 'cashier',
        verifyState: 'VERIFIED',
        lastCommit: '4b7de11',
        latestTag: 'v1.9.4',
      },
      {
        id: 'r_5',
        repoType: 'BACKEND',
        provider: 'BITBUCKET',
        repoProject: 'PAY',
        repoSlug: 'payment-ms',
        defaultBranch: 'main',
        urlPatterns: ['/api/pay/**'],
        verifyState: 'VERIFIED',
        lastCommit: 'e02aa5d',
        latestTag: 'v3.2.7',
      },
    ],
    urlMappings: [
      { id: 'm_4', pattern: '/api/pay/**', service: 'payment-ms', repoId: 'r_5' },
      { id: 'm_5', pattern: '/cashier/*', service: 'fe/cashier-web', repoId: 'r_4' },
    ],
    logging: {
      provider: 'ELASTIC',
      baseUrl: 'https://kibana.company.com/app/discover',
      indexPattern: 'payment-ms-*',
      versionMapping: 'CI_BUILD_NUMBER',
      fieldMap: {
        timestamp: '@timestamp',
        level: 'level',
        traceId: 'transactionId',
        message: 'msg',
        stackTrace: 'stack',
        service: 'app',
      },
      verifyState: 'VERIFIED',
      docCount7d: 884_210,
    },
    jira: {
      site: jiraSite,
      projectKey: 'PAY',
      issueType: 'Bug',
      descriptionTemplate: '问题描述 / 渠道与订单号 / 日志与 Trace / AI 诊断结论 / 建议修复',
      autoCreate: false,
    },
    uat: { pipelineId: 'payment-ms-uat', deployMethod: 'API_TRIGGER', enabled: true },
    capability: { aiDiagnosis: true, sourceAnalysis: true, autoFix: false, approvalMode: 'REVIEW_REQUIRED' },
    createdAt: iso(150),
    updatedAt: iso(6),
  },
  {
    id: 'p_cs',
    projectKey: 'customer-service',
    name: '客户服务',
    description: '工台、投诉与知识库',
    ownerId: 'u_zhao',
    access: { groupIds: ['g_cs', 'g_qa'], userIds: ['u_qian'] },
    status: 'ACTIVE',
    repos: [
      {
        id: 'r_6',
        repoType: 'FRONTEND',
        provider: 'GITHUB',
        repoProject: 'cs-frontend',
        repoSlug: 'workbench',
        defaultBranch: 'main',
        urlPatterns: [],
        verifyState: 'PENDING',
        lastCommit: '',
        latestTag: '',
      },
      {
        id: 'r_7',
        repoType: 'BACKEND',
        provider: 'BITBUCKET',
        repoProject: 'CS',
        repoSlug: 'customer-ms',
        defaultBranch: 'main',
        urlPatterns: ['/api/cs/**'],
        verifyState: 'VERIFIED',
        lastCommit: '77aa1c9',
        latestTag: 'v4.1.2',
      },
    ],
    urlMappings: [{ id: 'm_6', pattern: '/api/cs/**', service: 'customer-ms', repoId: 'r_7' }],
    logging: {
      provider: 'KIBANA',
      baseUrl: 'https://kibana.company.com/s/customer',
      indexPattern: 'customer-ms-*',
      versionMapping: 'COMMIT_HASH',
      fieldMap: {
        timestamp: '@timestamp',
        level: 'severity',
        traceId: 'trace.traceId',
        message: 'message',
        stackTrace: 'error.stacktrace',
        service: 'service.name',
      },
      verifyState: 'PENDING',
    },
    jira: {
      site: jiraSite,
      projectKey: 'CS',
      issueType: 'Task',
      descriptionTemplate: '问题描述 / 客户与工单号 / 日志与 Trace / AI 诊断结论',
      autoCreate: true,
    },
    uat: { pipelineId: '', deployMethod: 'WEBHOOK_DIRECT', enabled: false },
    capability: { aiDiagnosis: true, sourceAnalysis: false, autoFix: false, approvalMode: 'DISABLED' },
    createdAt: iso(96),
    updatedAt: iso(11),
  },
  {
    id: 'p_legacy',
    projectKey: 'legacy-portal',
    name: '旧版门户（已归档）',
    description: '2025 下线，保留历史 Case 查询',
    ownerId: 'u_zhang',
    access: { groupIds: ['g_fe'], userIds: [] },
    status: 'ARCHIVED',
    repos: [],
    urlMappings: [],
    logging: {
      provider: 'ELASTIC',
      baseUrl: 'https://kibana.company.com/app/discover',
      indexPattern: 'legacy-portal-*',
      versionMapping: 'TAG',
      fieldMap: {
        timestamp: '@timestamp',
        level: 'level',
        traceId: 'traceId',
        message: 'message',
        stackTrace: 'exception.stack_trace',
        service: 'service.name',
      },
      verifyState: 'FAILED',
    },
    jira: { site: jiraSite, projectKey: 'PORTAL', issueType: 'Bug', descriptionTemplate: '', autoCreate: false },
    uat: { pipelineId: '', deployMethod: 'WEBHOOK_DIRECT', enabled: false },
    capability: { aiDiagnosis: false, sourceAnalysis: false, autoFix: false, approvalMode: 'DISABLED' },
    createdAt: iso(420),
    updatedAt: iso(120),
  },
];

/** JIRA 工作流状态与流水线状态按 §9.2 保持一致 */
const STAGE_STATE: Record<
  Stage,
  {
    jira: JiraStatus;
    fix: FixPipelineStatus;
    uat: UatStatus;
    review: AnalysisReview;
    diagnosis: DiagnosisStatus;
    pr?: boolean;
  }
> = {
  ANALYZING: { jira: 'Analysis Ready', fix: 'PENDING_APPROVAL', uat: 'NONE', review: 'DONE', diagnosis: 'COMPLETED' },
  DEVELOPING: { jira: 'Fix Approved', fix: 'FIXING', uat: 'NONE', review: 'CONFIRMED', diagnosis: 'COMPLETED' },
  VERIFYING: { jira: 'In Review', fix: 'PR_CREATED', uat: 'NONE', review: 'CONFIRMED', diagnosis: 'COMPLETED', pr: true },
  DEPLOYING: { jira: 'In Deploy', fix: 'MERGED', uat: 'DEPLOYING', review: 'CONFIRMED', diagnosis: 'COMPLETED', pr: true },
  REJECTED: { jira: 'Rejected', fix: 'PR_REJECTED', uat: 'NONE', review: 'REJECTED', diagnosis: 'COMPLETED', pr: true },
  DONE: { jira: 'Done', fix: 'UAT_DEPLOYED', uat: 'SUCCESS', review: 'CONFIRMED', diagnosis: 'COMPLETED', pr: true },
};

interface Seed {
  p: string;
  n: number;
  title: string;
  type: FindingType;
  sev: Severity;
  env: Environment;
  stage: Stage;
  assignee: string;
  service: string;
  age: number;
  touched?: number;
  drift?: JiraStatus;
  case?: string;
}

const SEEDS: Seed[] = [
  {
    p: 'p_acct', n: 1287, title: 'KYC 提交后资料页一直转圈，账户状态未更新', type: 'BACKEND', sev: 'Critical',
    env: 'PROD', stage: 'ANALYZING', assignee: 'u_sun', service: 'account-ms', age: 1,
  },
  {
    p: 'p_acct', n: 1286, title: '切换语言后姓名拼音字段被清空', type: 'FRONTEND', sev: 'Major', env: 'PROD',
    stage: 'ANALYZING', assignee: 'u_qian', service: 'fe/account-web', age: 2,
  },
  {
    p: 'p_acct', n: 1281, title: '额度查询接口 504，customer-adapter 连接池打满', type: 'INTEGRATION', sev: 'Critical',
    env: 'PROD', stage: 'DEVELOPING', assignee: 'u_sun', service: 'customer-adapter', age: 4, drift: 'Fix Approved',
  },
  {
    p: 'p_acct', n: 1279, title: '登录态过期后未跳转 SSO，页面白屏', type: 'FRONTEND', sev: 'Major', env: 'UAT',
    stage: 'DEVELOPING', assignee: 'u_qian', service: 'fe/account-web', age: 5,
  },
  {
    p: 'p_acct', n: 1274, title: '批量导出 CSV 在大数据量下 OOM', type: 'BACKEND', sev: 'Minor', env: 'PROD',
    stage: 'VERIFYING', assignee: 'u_sun', service: 'account-ms', age: 8,
  },
  {
    p: 'p_acct', n: 1271, title: '实名认证回调重复消费导致状态回滚', type: 'BACKEND', sev: 'Critical', env: 'PROD',
    stage: 'VERIFYING', assignee: 'u_zhang', service: 'account-ms', age: 10, drift: 'Ready to Merge',
  },
  {
    p: 'p_acct', n: 1266, title: '头像上传成功后缩略图仍显示旧图（缓存未失效）', type: 'FRONTEND', sev: 'Minor',
    env: 'PROD', stage: 'DEPLOYING', assignee: 'u_qian', service: 'fe/account-web', age: 13,
  },
  {
    p: 'p_acct', n: 1258, title: '账户余额四舍五入误差导致对账差异', type: 'BACKEND', sev: 'Major', env: 'PROD',
    stage: 'DONE', assignee: 'u_sun', service: 'account-ms', age: 21,
  },
  {
    p: 'p_acct', n: 1252, title: '手机号更换验证码倒计时未按秒刷新', type: 'FRONTEND', sev: 'Minor', env: 'DEV',
    stage: 'REJECTED', assignee: 'u_qian', service: 'fe/account-web', age: 25,
  },
  {
    p: 'p_pay', n: 431, title: '招商银行渠道回调签名校验失败，订单悬挂', type: 'BACKEND', sev: 'Critical', env: 'PROD',
    stage: 'DEVELOPING', assignee: 'u_zhou', service: 'payment-ms', age: 2, drift: 'In Review',
  },
  {
    p: 'p_pay', n: 429, title: '收银台金额小数位展示为 0.0', type: 'FRONTEND', sev: 'Major', env: 'PROD',
    stage: 'ANALYZING', assignee: 'u_zhou', service: 'fe/cashier-web', age: 3,
  },
  {
    p: 'p_pay', n: 425, title: '退款接口幂等键缺失导致重复退款', type: 'BACKEND', sev: 'Critical', env: 'PROD',
    stage: 'VERIFYING', assignee: 'u_li', service: 'payment-ms', age: 7,
  },
  {
    p: 'p_pay', n: 418, title: '对账文件解析在跨月边界漏单', type: 'BACKEND', sev: 'Major', env: 'UAT',
    stage: 'DEPLOYING', assignee: 'u_zhou', service: 'payment-ms', age: 12,
  },
  {
    p: 'p_pay', n: 410, title: '渠道超时后前端未提示可重试', type: 'INTEGRATION', sev: 'Minor', env: 'PROD',
    stage: 'DONE', assignee: 'u_zhou', service: 'payment-ms', age: 28,
  },
  {
    p: 'p_cs', n: 96, title: '工单列表按处理人筛选无结果', type: 'BACKEND', sev: 'Major', env: 'PROD',
    stage: 'ANALYZING', assignee: 'u_wu', service: 'customer-ms', age: 1,
  },
  {
    p: 'p_cs', n: 92, title: '知识库全文检索高亮丢失', type: 'FRONTEND', sev: 'Minor', env: 'PROD',
    stage: 'VERIFYING', assignee: 'u_wu', service: 'cs-workbench', age: 6,
  },
  {
    p: 'p_cs', n: 88, title: '投诉单转派后 SLA 计时未重置', type: 'BACKEND', sev: 'Critical', env: 'PROD',
    stage: 'DONE', assignee: 'u_zhao', service: 'customer-ms', age: 15,
  },
  {
    p: 'p_cs', n: 83, title: '工台导出 Excel 在 IE 内核下乱码', type: 'FRONTEND', sev: 'Minor', env: 'STAGE',
    stage: 'REJECTED', assignee: 'u_wu', service: 'cs-workbench', age: 30,
  },
];

const FIX_LOGS: Record<Stage, { actor: string; message: string }[]> = {
  ANALYZING: [
    { actor: 'system', message: 'Case 采证完成，Evidence 12 条' },
    { actor: 'llm', message: '诊断产出 Finding，置信度 0.86' },
  ],
  DEVELOPING: [
    { actor: 'owner', message: '批准修复，进入自动修复流程' },
    { actor: 'llm', message: 'Fix Agent 已修改 3 个文件，单测通过' },
  ],
  VERIFYING: [
    { actor: 'owner', message: '批准修复，进入自动修复流程' },
    { actor: 'llm', message: 'PR 已创建，等待 Bitbucket Review' },
  ],
  DEPLOYING: [
    { actor: 'reviewer', message: 'PR Approved' },
    { actor: 'bitbucket', message: 'PR Merged → 触发 UAT Pipeline' },
  ],
  REJECTED: [
    { actor: 'reviewer', message: 'PR Declined：改动影响面过大，需拆分' },
  ],
  DONE: [
    { actor: 'pipeline', message: 'UAT 发布成功' },
    { actor: 'jira', message: 'Transition → Done，关单' },
  ],
};

function buildTicket(s: Seed, i: number): Ticket {
  const st = STAGE_STATE[s.stage];
  const project = PROJECTS.find((p) => p.id === s.p)!;
  const jiraKey = `${project.jira.projectKey}-${s.n}`;
  const repoSlug = s.service.startsWith('fe/') ? s.service.slice(3) : s.service;
  const createdAt = iso(s.age, i);
  return {
    id: `t_${jiraKey}`,
    projectId: s.p,
    jiraKey,
    jiraUrl: `${jiraSite}/browse/${jiraKey}`,
    title: s.title,
    jiraStatus: st.jira,
    jiraStatusRemote: s.drift ?? st.jira,
    findingType: s.type,
    severity: s.sev,
    environment: s.env,
    assigneeId: s.assignee,
    defaultAssigneeId: project.ownerId,
    diagnosis: st.diagnosis,
    analysisReview: st.review,
    fix: {
      status: st.fix,
      prUrl: st.pr ? `https://bitbucket.company.com/projects/${project.repos[0]?.repoProject}/repos/${repoSlug}/pull-requests/${s.n}` : undefined,
      prBranch: st.pr ? `fix/${jiraKey}-ai` : undefined,
      approvedById: s.stage === 'ANALYZING' ? undefined : project.ownerId,
      logs: (FIX_LOGS[s.stage] ?? []).map((l, k) => ({
        at: iso(Math.max(s.age - (k + 1) * 0.5, 0)),
        actor: l.actor,
        message: l.message,
      })),
    },
    uat: st.uat,
    caseKey: `CTX-${1000 + i}`,
    findingKey: `FND-${2000 + i}`,
    service: s.service,
    createdAt,
    updatedAt: iso(s.touched ?? Math.max(s.age - 0.5, 0)),
    drift: s.drift ? `JIRA 已流转到 ${s.drift}` : undefined,
  };
}

export const TICKETS: Ticket[] = SEEDS.map(buildTicket);

const FINDING_TEXT: Record<FindingType, { rootCause: string; fix: string; file: string }> = {
  BACKEND: {
    rootCause:
      '下游 customer-adapter 连接池 maxActive=8 在高并发下耗尽，`/api/account/quota` 平均等待 4.2s 后由网关侧超时抛 504。',
    fix: '将连接池扩容至 32 并增加获取超时降级；为 quota 调用补充熔断与重试退避。',
    file: 'account-ms/src/main/java/com/company/account/QuotaService.java',
  },
  FRONTEND: {
    rootCause: '`onLanguageChange` 里 setFieldsValue 覆盖了 namePinyin，且未从接口回填该字段。',
    fix: '切换语言时仅更新展示字段，namePinyin 保留 store 原值并在提交前回填。',
    file: 'account-web/src/pages/Profile/index.tsx',
  },
  INTEGRATION: {
    rootCause: '前端按旧契约读取 data.result.list，后端 v5.8.0 已改为 data.items，导致列表渲染为空。',
    fix: '统一走 API 适配层读取 items，并补充契约测试锁定字段。',
    file: 'account-web/src/services/customer.ts',
  },
};

/** Case 由工单反推生成，保证列表与详情数据一致 */
export function buildCase(ticket: Ticket): Case {
  const project = PROJECTS.find((p) => p.id === ticket.projectId)!;
  const text = FINDING_TEXT[ticket.findingType];
  const finding: LegacyFinding = {
    id: `f_${ticket.findingKey}`,
    findingKey: ticket.findingKey,
    type: ticket.findingType,
    title: ticket.title,
    rootCause: text.rootCause,
    aiConfidence: 0.86,
    systemConfidence: 0.71,
    verificationStatus: ticket.analysisReview === 'CONFIRMED' ? 'VERIFIED' : 'AI_SUGGESTED',
    locations: [{ file: text.file, line: 128 }],
    recommendedFix: text.fix,
    evidenceIds: ['EVD-301', 'EVD-302'],
    jiraKey: ticket.jiraKey,
  };
  return {
    id: `c_${ticket.caseKey}`,
    caseKey: ticket.caseKey,
    projectId: ticket.projectId,
    title: ticket.title,
    environment: ticket.environment,
    severity: ticket.severity,
    pageUrl: `https://portal.company.com/account/profile?from=todo`,
    buildVersion: project.repos[1]?.latestTag ?? 'v1.0.0',
    reporter: `${project.name} 值班`,
    reportedAt: ticket.createdAt,
    status: ticket.diagnosis === 'RUNNING' ? 'ANALYZING' : 'JIRA',
    description: `${ticket.title}。复现路径：登录 → 账户资料 → 触发对应操作，稳定复现。`,
    network: [
      { id: 'EVD-301', kind: 'NETWORK', label: 'POST /api/account/quota · 504 · 4210ms', detail: 'traceId=2f81c0…e7，响应体为空，网关 timeout' },
      { id: 'EVD-304', kind: 'NETWORK', label: 'GET /api/customer/adapter/status · 200 · 310ms', detail: '用于关联上下文，无异常' },
    ],
    consoleLogs: [
      { id: 'EVD-302', kind: 'CONSOLE', label: 'TypeError: cannot read properties of undefined (reading "items")', detail: 'at ProfilePage.tsx:212 · 3 次重复' },
    ],
    stacks: [
      { id: 'EVD-303', kind: 'STACK', label: 'java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available', detail: 'requestTimeout=3000ms, active=8, idle=0, waiting=27' },
    ],
    evidenceChain: [
      { node: ticket.caseKey, label: 'Context 上报' },
      { node: 'EVD-301', label: 'Network' },
      { node: 'EVD-303', label: '日志堆栈' },
      { node: ticket.findingKey, label: 'Finding' },
      { node: ticket.jiraKey, label: 'JIRA' },
    ],
    findings: [finding],
  };
}

export const AUDIT_LOGS: AuditLogItem[] = [
  { id: 'a1', at: iso(0, 2), actor: 'admin@company.com', action: 'ROLE_GRANT', target: 'lisi@company.com', detail: 'DEVELOPER → PROJECT_OWNER', ip: '10.20.3.7', result: 'SUCCESS' },
  { id: 'a2', at: iso(0, 4), actor: 'zhangsan@company.com', action: 'PROJECT_CREATE', target: 'account-center', detail: '新增后端仓库 customer-adapter 绑定', ip: '10.20.3.11', result: 'SUCCESS' },
  { id: 'a3', at: iso(1), actor: 'qianqi@company.com', action: 'LOGIN', target: 'GOOGLE OAuth', detail: '邮箱域名白名单校验通过', ip: '10.20.5.42', result: 'SUCCESS' },
  { id: 'a4', at: iso(1, 8), actor: 'unknown@external.io', action: 'LOGIN', target: 'GOOGLE OAuth', detail: '邮箱域名不在白名单', ip: '203.0.113.9', result: 'DENIED' },
  { id: 'a5', at: iso(2), actor: 'lisi@company.com', action: 'FIX_APPROVE', target: 'PAY-425', detail: '批准 AI 修复并触发 Fix Agent', ip: '10.20.4.19', result: 'SUCCESS' },
  { id: 'a6', at: iso(3), actor: 'system', action: 'SYNC_JIRA', target: 'payment-gateway', detail: '轮询兜底，14 条工单状态同步，2 条变更', ip: '—', result: 'SUCCESS' },
  { id: 'a7', at: iso(4), actor: 'zhaowu@company.com', action: 'ACCESS_UPDATE', target: 'customer-service', detail: '新增授权组：质量保障组', ip: '10.20.6.8', result: 'SUCCESS' },
];

export const ENVIRONMENT_OPTIONS: Environment[] = ['PROD', 'UAT', 'STAGE', 'DEV'];
